# Generated by Django 5.1.1 on 2024-09-11 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fabrication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='code_item',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LesProduits.status'),
        ),
    ]
