# Generated by Django 5.1.1 on 2024-09-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0002_status_product_fabrication_date_product_price_ht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='code_item',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
